variable "enabled" {
  description = "Whether the EKS cluster, node group, and access entries exist. false removes them (~$3.10/day) and keeps the free VPC and IAM roles."
  type        = bool
  default     = true
}

variable "cluster_name" {
  description = "Name of the EKS cluster, also used to prefix its VPC, subnets, and IAM roles."
  type        = string
  default     = "apotterlab"
}

variable "kubernetes_version" {
  description = "EKS control plane version. null takes the EKS default at creation; set it explicitly to upgrade."
  type        = string
  default     = null
}

variable "vpc_cidr" {
  description = "CIDR block for the cluster VPC. Must not overlap the lab VPCs (10.0.0.0/16, 10.1.0.0/16)."
  type        = string
  default     = "10.2.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for the public subnets, one per AZ. EKS requires at least two AZs."
  type        = list(string)
  default     = ["10.2.1.0/24", "10.2.2.0/24"]

  validation {
    condition     = length(var.public_subnet_cidrs) >= 2
    error_message = "EKS needs subnets in at least two availability zones."
  }
}

variable "cluster_admin_arns" {
  description = "IAM principal ARNs granted cluster-admin through EKS access entries."
  type        = list(string)
  # Humans only; CI's in-cluster access is defined in app_access.tf.
  default = [
    # Console user; without an entry the EKS console can't list pods, nodes, or other Kubernetes objects.
    "arn:aws:iam::549610932637:user/apotter",
  ]
}

variable "node_instance_type" {
  description = "Instance type for the managed node group. This account is on the AWS Free plan, which only launches free-tier-eligible types."
  type        = string
  default     = "t3.small"
}

variable "node_desired_size" {
  description = "Desired number of worker nodes."
  type        = number
  default     = 1
}

variable "node_min_size" {
  description = "Minimum number of worker nodes."
  type        = number
  default     = 1
}

variable "node_max_size" {
  description = "Maximum number of worker nodes."
  type        = number
  default     = 2
}

variable "node_capacity_type" {
  description = "ON_DEMAND or SPOT."
  type        = string
  default     = "ON_DEMAND"

  validation {
    condition     = contains(["ON_DEMAND", "SPOT"], var.node_capacity_type)
    error_message = "node_capacity_type must be ON_DEMAND or SPOT."
  }
}

variable "db_subnet_cidrs" {
  description = "Private subnets for RDS, one per AZ (RDS needs at least two). No route to the internet."
  type        = list(string)
  default     = ["10.2.11.0/24", "10.2.12.0/24"]

  validation {
    condition     = length(var.db_subnet_cidrs) >= 2
    error_message = "RDS needs subnets in at least two availability zones."
  }
}

variable "db_instance_class" {
  description = "RDS instance class. The AWS Free plan only allows db.t3.micro and db.t4g.micro."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_engine_version" {
  description = "PostgreSQL major version; minor versions upgrade automatically."
  type        = string
  default     = "18"
}

variable "db_allocated_storage" {
  description = "Storage in GiB."
  type        = number
  default     = 20
}

variable "db_name" {
  description = "Initial database created on the instance."
  type        = string
  default     = "app"
}

variable "db_username" {
  description = "Master username. The password is generated by RDS and stored in Secrets Manager."
  type        = string
  default     = "postgres"
}

variable "app_namespace" {
  description = "Namespace the kubernetes-deploy app runs in. Created by Terraform."
  type        = string
  default     = "production"
}

variable "app_service_account" {
  description = "ServiceAccount the app's pods run as (created by the Helm chart). Pod Identity maps it to the DB-secret role."
  type        = string
  default     = "hello-world"
}

variable "deploy_role_arn" {
  description = "IAM role the kubernetes-deploy workflow uses for helm; gets edit access in app_namespace only."
  type        = string
  default     = "arn:aws:iam::549610932637:role/github-actions-deploy"
}
